version: "3.8"
services:
  web:
    container_name: php-apache-crypto-converter
    networks:
      - crypto-converter-network
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
      - 443:443
  db:
    container_name: mysql-db-crypto-converter
    networks:
      - crypto-converter-network
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_DATABASE: crypto_converter
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #OR
      # So you don't have to use root, but you can if you like
      #MYSQL_USER: 'user'
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'password'
      # Password for root access
      #MYSQL_ROOT_PASSWORD: 'password'
    ports:
    # <Port exposed> : < MySQL Port running inside container>
    - "3307:3306"
    #expose:
    # Opens port 3306 on the container for other containers
    #- "3306"
    # Where our data will be persisted
    volumes:
    - ./deployment/mysql:/var/lib/mysql
# Names our volume
volumes:
  my-db:

networks:
  crypto-converter-network:
    driver: bridge
